artsy/artsy-passport

- index.coffee
If a user goes to any page with a .tmp account this will redirect them to the one last step url
> @craigspaeth: Ensure one last step

- README.md
- example/index.coffee
- example/login.jade
- example/onelaststep.jade
- index.coffee
- npm-shrinkwrap.json
- package.json
- test/index.coffee
The fix is actually built-in and very simple. I'll show you where it is. The rest of these changes involve...
* Shuffling around code for better organization
* Updated documentation to be more helpful
* Updated tests and example app to reflect the many small updates we've made over time
* Updated node module dependencies
* Remove the old `secureHash` related code that wasn't doing anything
> @craigspaeth (cc @dblock): Add state: true for Facebook auth

- lib/app/analytics.coffee
- package.json
- test/app/analytics.coffee
Related to marketing modals, I'll explain inline.
> @broskoski: Pass query params for tracking acquisition initiatives as well

- lib/passport/callbacks.coffee
Re: https://github.com/artsy/artsy-passport/pull/93
And https://github.com/artsy/force/pull/767
> @craigspaeth - Throw error if account not found when logging in with Twitter

- lib/passport/callbacks.coffee
- package.json
> Defensive params check

- lib/app/redirectback.coffee
@craigspaeth I think this fixes https://github.com/artsy/artsy-passport/issues/101.
I can check this out in the sample project in artsy-passport tomorrow
> [hold] delete session data before redirecting

- lib/app/lifecycle.coffee
- package.json
- test/app/lifecycle.coffee
Going through random Sentry errors reported for Force, and noticed this [bit of noise](https://sentry.io/artsynet/force-production/issues/256008878/) we can handle for all the h4x0rs.
> Capture IP blocked errors from Facebook

- lib/app/lifecycle.coffee
- package.json
- test/app/lifecycle.coffee
Fixes https://github.com/artsy/force/issues/1407
> @broskoski: Added redirect back to personalize after told to login

- .gitignore
- lib/app/analytics.coffee
- lib/app/index.coffee
- lib/app/lifecycle.coffee
- lib/app/locals.coffee
- lib/app/logout.coffee
- lib/app/redirectback.coffee
- lib/app/token_login.coffee
- lib/app/twitter_last_step.coffee
- lib/index.coffee
- lib/passport/callbacks.coffee
- lib/passport/index.coffee
- lib/passport/serializers.coffee
- package.json
Looks like I was wrong with using browserify for trying to ship a build to NPM - moved it to the coffeescript compiler.  Verified via `yarn link` on reaction force as working.
> Use the coffee-script compiler to bundle the app instead of browserify

- .npmignore
- package.json
Yarn link would work correctly, but not a release.
> Changes for deploying correct releases

- lib/index.coffee
> @mzikherman => Explicitly export sanitize redirect as it is used as a helper method 

- lib/index.coffee
- sanitize-redirect.js
> @mzikherman => Point to dist file for helper export

- package.json
- yarn.lock
I released this as 1.1.0, included in https://github.com/artsy/force/pull/3039
> @damassi => Bump passport lib and release 1.1.0

- .circleci/config.yml
- lib/passport/callbacks.coffee
- package.json
- yarn.lock
Moves the request from `query` to  `send`.
> Update post body

- lib/app/lifecycle.coffee
- package.json
- test/app/lifecycle.coffee
Sends recaptcha_token to gravity with other signup args.
> Include recaptcha_token in signup args

- lib/app/lifecycle.coffee
- package.json
Kills the following error in consuming clients:
> Remove deprecated res send

- lib/app/lifecycle.coffee
- package.json
- test/app/lifecycle.coffee
Addresses https://artsyproduct.atlassian.net/browse/FX-1189
> XHR errors can be parsed for errors on admin signup

- example/loggedin.jade
- example/login.jade
- example/nocsrf.jade
- example/personalize.jade
- lib/app/index.coffee
- lib/app/lifecycle.coffee
- lib/app/locals.coffee
- lib/options.coffee
- lib/passport/callbacks.coffee
- lib/passport/index.coffee
- package.json
- test/app/lifecycle.coffee
- test/passport/callbacks.coffee
- yarn.lock
https://artsyproduct.atlassian.net/browse/MX-216
- Fix spacing in account link error
- Add apple paths and Oauth calls
- Add passport-apple dependency
- Init strategy for apples sign in, add env vars
- Add routes for sign in with apple
- Add apple in example apple
> [MX-216] - Sign in with apple routes and callbacks, see details

- .npmignore
- package.json
- Bumps version to a stable v1.2.0
- Keeps some unwanted files out of the package tarball
> Prepare v1.2.0

- yarn.lock
https://github.com/artsy/passport-local-with-otp/releases/tag/v0.3.1
> Bump @artsy/passport-local-with-otp dependency

- package.json
5bbe35661bcb70a8216e63c0462ce3274a8cc425...409cdd0e3aa726e4b5881da2ed8d64da5cfdd423
> Prep v1.3.0

- package.json
- yarn.lock
- Pins forked passport apple dependency to specific commit
- Bumps version in package.json
> Prep for release 1.5.0 #trivial

- lib/passport/callbacks.coffee
- test/passport/callbacks.coffee
- Passes down idToken to callbacks for creating a user
> fix: pass down idToken to create user callbacks #trivial

- renovate.json
Sets @icirellik as assignee since I can't fill that role anymore 😢 
cc @joeyAghion
> Set Cameron as renovate assignee

- package.json
- yarn.lock
Reverts artsy/artsy-passport#185
> Revert "Bump superagent from 1.8.4 to 6.1.0"

- lib/app/sanitize_redirect.js
Adopts inclusive language in `sanitize_redirect.js`, resolves issue: https://github.com/artsy/artsy-passport/issues/188 as per https://github.com/artsy/README/issues/427
> chore: Adopt inclusive language in sanitize_redirect.js
