README.md, index.coffee
This allows us to pass in an XAPP token when artsy-passport is initialized rather than relying on it to be stored in `res.locals`.
=> @craigspaeth - pass in xapp token 

README.md, index.coffee, test/index.coffee
This gives the ability to pass a signupRedirect option:
```
app.use artsyPassport _.extend config,
CurrentUser: CurrentUser
signupRedirect: '/personalize'
```
Social auth seems to redirect multiple times so this will only set a session variable that can be handled on the app side after the user is fully logged in.
=> @craigspaeth - signupRedirect option

README.md, example/client.coffee, example/index.coffee, example/nocsrf.jade, example/public/client.js, index.coffee, index.js, package.json, test/index.coffee
This copy + pastes your trustTokenMiddleware code from Force and adds csrf middleware. Since the csrf is a breaking change anyways I decided to rename `SECURE_ARTSY_URL` to just `ARTSY_URL` which aligns with [artsy-xapp](https://github.com/artsy/artsy-xapp) and since we're SSL everything now the former seems redundant.
=> @dzucconi: CSRF required for login form and trust token login support

Makefile, example/index.coffee, index.coffee, package.json, test/index.coffee
Twitter [doesn't support OAuth2 for users](https://twittercommunity.com/t/is-the-state-parameter-supported/1889), so we have to add this `state` param csrf thing ourselves (it's just a `state: true` passport config for Facebook). Basically the gist is you generate a token that you pass to Twitter before authorizing our Twitter app access and check that when Twitter sends you back to Artsy (at the `/users/auth/twitter/callback` callback url) it includes that token as a `state` query param.
Or at least that's what I think is involved [OAuth... ( -__- )](http://hueniverse.com/2012/07/26/oauth-2-0-and-the-road-to-hell/).—we'll see if it passes our bounty program h4x0rz's approval.
=> @broskoski: State param csrf check for Twitter auth

README.md, lib/app/redirectback.coffee, lib/app/sanitize_redirect.coffee, lib/index.coffee, package.json, test/app/sanitize_redirect.coffee
https://github.com/artsy/artsy-passport/issues/68
The problem here seems to be due to how client-side those whitespace characters are interpreted and how that gets through sanitizing... just stripping whitespace now and will re-introduce to Force.
=> @craigspaeth (cc @dzucconi): Address open redirect issue

lib/app/lifecycle.coffee, lib/app/redirectback.coffee, package.json, test/app/lifecycle.coffee
This will use Gravity's trust_token login scheme to log a user in to Gravity after logging into Artsy Passport apps (Force + MG). This will be convenient for apps like CMS and Writer which use Gravity as an OAuth provider b/c it means a user who logs in to the Artsy website, should be able to seamlessly be logged into those apps as well.
=> @craigspaeth: Single sign on to Gravity after logging in

lib/app/lifecycle.coffee, test/app/lifecycle.coffee
In the process of authenticating with the Facebook provide in passport the query redirect is lost [#4379](https://github.com/artsy/force/issues/4379). This assigns the value of the query redirect to the session redirect so that it persists.
This is my first stab at working in artsy-passport so let me know if I'm missing anything (or need to add more tests). 
cc: @broskoski
=> @craigspaeth: assign the query redirect to session redirect so it is not lost

README.md, lib/app/index.coffee, package.json
When a user signs up through twitter they see this UI so we can collect their email
One of dB's security researchers pointed out that there isn't CSRF protection on this—which could be exploited by...
1. User logs in to Artsy
2. User opens up email from Nigerian prince to attacker.com
3. User submits a form to send bitcoin to said prince on attacker.com
4. Said form actually POSTs to artsy.net/users/auth/twitter/email (the "one last step form endpoint) and has a hidden field with `name='email' value='haxor@nigerianprince.com'` 
5. User's email gets updated to haxor@nigerianprince.com and user gets redirected to Artsy's personalize flow b/c we don't enforce CSRF
=> @broskoski: CSRF protection on "one last step"

README.md, lib/app/analytics.coffee, lib/app/index.coffee, lib/app/lifecycle.coffee, lib/app/redirectback.coffee, package.json, test/app/analytics.coffee, test/app/lifecycle.coffee
This adds Segment's node library to implement signup tracking at a granular, server-side, level. This is going to be important for user acquisition initiatives on the Collector Experience team. cc @anipetrov
=> @kanaabe: Add segment tracking to signup

lib/app/analytics.coffee, package.json, test/app/analytics.coffee
I had originally tried using Express'es [req.param()](http://expressjs.com/en/api.html#req.param) to pull out either the body or query params, then realized it was deprecated, so I naively used `req.params` instead, which is meant only for routing params like `/artwork/:id`. Derp. This just uses `req.body` because signing up would always be a POST request anyways. (I'll point out how this fits in, in my Force/MG PR coming soon).
=> @kanaabe: Fix to pass along modal_id and acquisition_initiative via req.body instead

lib/app/lifecycle.coffee, lib/app/redirectback.coffee
I think https://github.com/artsy/artsy-passport/commit/6a10788e53e6efd932a0aff9c711f23e039dc90c may have included a regression, where we can't skip onboarding during social auth.
You can see this in production now by clicking 'Bid' on an auction work and signing up with Facebook. You get dumped into the personalize flow and never make it back to the bid screen. I'm pretty sure this used to work, and that recent commit looks suspicious.
For the artist page CTA, I also want the ability to skip onboarding after a social signup, so this just adds support for a `skip-onboarding=true` query param.
=> @craigspaeth => Allow social auth to skip onboarding

lib/app/twitter_last_step.coffee
Rewords and removes the link (which isn't parsed anyway):
=> @craigspaeth - Update error message

lib/app/lifecycle.coffee, lib/passport/callbacks.coffee, package.json, test/app/lifecycle.coffee, test/passport/callbacks.coffee
Gravity pulls out the user agent header to API requests and persists it to [fields on its user model](https://github.com/artsy/gravity/blob/master/app/models/domain/user.rb#L64). This worked well when Artsy was one glorious Backbone monolith that made all its requests client-side and the browser sent that for free. However, now that we send a lot of things server-side, including access token/account creation API requests, we don't get that for free anymore and many users have a `node-superagent-blah-blah` set as that field. The analytics team uses these Gravity-level fields often so we can be helpful and have the server using Artsy Passport to pass the user agent through these requests.
=> @broskoski: Pass user agent through signup and login

lib/app/analytics.coffee, lib/app/index.coffee, test/app/analytics.coffee
We'd like to instrument login tracking in the loyalty app, but realized that we could maybe just consolidate login tracking within `artsy-passport` (similarly to the sign up tracking going on).
In Force/Micro-g, we basically just do: https://github.com/artsy/force/blob/4348d1d08f8036d9aa76d03dfedd2c7887d05fd8/desktop/analytics/account_creation.js#L75
So, this just moves that (along with the user id) here. Then, we'd release a new version of this lib, and update Force to use it as well as removing those calls from Force.
What do you think?
=> @craigspaeth => Track logins with Segment

lib/app/lifecycle.coffee, package.json, test/app/lifecycle.coffee
There's two other random social auth errors reported in Sentry and I think we should go ahead and surface those to the user on the login screen instead of landing them on our generic error handler page which gets reported as errors to Sentry.
e.g.
=> Render random social auth errors on the login screen

lib/passport/callbacks.coffee, package.json, test/passport/callbacks.coffee
Solves https://github.com/artsy/force/issues/1390
I missed a spot when I [tried to pass user agent through our Gravity calls](https://github.com/artsy/artsy-passport/pull/99)
=> @mzikherman: Pass user agents through Facebook signups

lib/app/lifecycle.coffee
Paired with @erikdstock , we made this change in Force's local `node_modules/` and confirmed it works as expected.
We have some Gravity changes that will be using this value.
Question: are you the right person to help us publish this? It seems like you're the only collaborator on https://www.npmjs.com/package/artsy-passport that is still at the company 🙂
=> @orta => Propagate referer when signing up via email/password

lib/app/lifecycle.coffee, lib/passport/callbacks.coffee
This PR updates artsy-passport to add a signup_intent parameter to gravity requests for new account creation, drawing it from either
- the `signupIntent` key for local account creation or 
- using the query string key `signup-intent` + session storage for social/facebook oauth account creation.
I'm not 💯 that I hit every note correctly here.
=> @mzikherman => pass signup_intent to gravity user account creation

lib/app/lifecycle.coffee, lib/passport/callbacks.coffee, package.json
This updates artsy-passport to save new fields for gdpr compliance on account creation. It should be relatively straightforward.
I changed this to a WIP while I figure out how I'm going to approach sending these params during social login.
Related: artsy/force#2244
=> save accepted_terms_of_service & receive_emails at signup

lib/passport/callbacks.coffee
Uses the `extend` in favor of the spread (`...`) syntax because the version of coffeescript we are using doesn't support the spread.
=> @erikdstock: uses extend in favor the spread syntax

lib/app/lifecycle.coffee
cc @mzikherman - A helper in our backbone views was used to account for the AB test + presence of 2 checkboxes, and so we needed to make this property name consistent whether in a url or signup POST body.
=> align gdpr property names

lib/app/lifecycle.coffee, lib/passport/callbacks.coffee, package.json
Mimics `sign_up_intent` to pass in the referer directly instead of getting it from req. I kept the places where we set a Referer like [here](https://github.com/artsy/artsy-passport/blob/master/lib/app/lifecycle.coffee#L38) to ensure we can use both up until we flip the switch in Gravity.
=> @mzikherman => Use explicit referer instead of on the request

README.md, package.json
I accidentally published 1.0.9 to npm without compiling first -- didn't realize this was part of the step! This bumps the version again so we can actually use it and adds some documentation around how to publish.
=> @mzikherman => Bump passport version and update docs

lib/app/lifecycle.coffee, lib/passport/callbacks.coffee, package.json
This is needed in order to pass the new gdpr properties in force (desktop/mobile).
=> @l2succes: replaces receive_emails with agreed_to_receive_emails

lib/options.coffee
Adds field `recaptcha_token` to accepted params for signup. This enables us to pass the field to Gravity for validation.
Have tested this linked in Force and signups complete without errors when sending this data with requests.
=> Add recaptcha_token to allowed userKeys

lib/app/logout.coffee
Relevant docs:
https://stackoverflow.com/questions/31641884/does-passports-logout-function-remove-the-cookie-if-not-how-does-it-work
I think the sequence of events we see is:
- you get a cookie for 1 day with an `id`. theres no `user`
- when you login, there's a `user` there, so we can correctly be auth'ed/unauth'ed
- when you logout, we clear `user` from that cookie. still correctly auth'ed/unauth'ed
- but, a stale `id` (maybe other stuff?) exists
=> @joeyAghion => [Logout] Make sure to clear session explicitly when logging out

lib/passport/callbacks.coffee
Name is passed back as a dictionary for sign in with apple and causing sign up failures in gravity which expects a string:
https://github.com/nicokaiser/passport-apple#which-fields-are-provided-in-the-user-profile
=> Fix name parsing on sign up with apple

lib/app/lifecycle.coffee, lib/passport/callbacks.coffee, lib/passport/index.coffee, package.json, test/passport/callbacks.coffee, yarn.lock
https://artsyproduct.atlassian.net/browse/TRUST-211
This PR changes the Passport strategy used by this library…
- from https://github.com/jaredhanson/passport-local
- to https://github.com/artsy/passport-local-with-otp
- (our new OTP-compatible fork of `passport-local`)
We increment the major version number of this package (to v2.0.0) because it is a breaking change that will require code changes in Force once it is imported there.
I'm assuming that major version bump will also [prevent auto-merging](https://github.com/artsy/renovate-config/blob/f330e4f8631d00328bedc97710d5a30c1d86f656/lib/config.js#L13-L18) of this change into Force (by Renovate), thus allowing us to adequately QA this via review app before merging manually.
=> Switch to passport-local-with-otp strategy to support 2FA

lib/app/forwarded_for.coffee, lib/app/lifecycle.coffee, lib/app/logout.coffee, lib/app/token_login.coffee, test/app/lifecycle.coffee
This PR copies [the pattern between Force and Metaphysics](https://github.com/artsy/force/blob/e908f2453b7b077b2ec4294e03cbfabf13dde802/src/lib/metaphysics2.coffee) for appending the end user's IP address to a `X-Forwarded-For` header. This is useful when, e.g., end users' browsers POST to `/sign_up` and Force translates that into a POST from its server-side to Gravity's `/api/v1/user` endpoint.
Don't merge this yet because:
* When I run Force with this locally, I get a strange error about a nearby header value (`Invalid value "undefined" for header "X-Xapp-Token"`). Maybe we can look at it? My set-up or config must be wrong.
* Should this use `req.ip` or `req.connection.remoteAddress`? Force uses the former for geocoding, but the latter when setting `X-Forwarded-For` on its requests to …
=> Set X-Forwarded-For when signing up and logging in

lib/passport/callbacks.coffee, lib/passport/index.coffee, package.json, test/passport/callbacks.coffee, yarn.lock
This passes the JWT from sign in with apple back to our api for verification, see slack thread for details:
https://artsy.slack.com/archives/CN8S32FJR/p1599838945258600
- Points to an artsy fork of a passport-apple implementation with additional change of passing back entire id token: https://github.com/artsy/passport-apple/pull/1/files
- Passes back the idToken in callbacks to our apis
- Changes some minor parameter names for the new forked passport-apple version
Note:
I tested this by installing in locally running force and signing in, initially had troubles with xapp token not being passed in header I believe due to duplicate node_modules but if someone more familiar with this repo wants to pair on making sure this is working correctly would be appreciated.
=> Apple sign in pass token to gravity

.autorc, .circleci/config.yml, package.json, yarn.lock
Updates CI config to add `auto` orb and publishing package via CI. 
<details>
<summary>📦 Published PR as canary version: <code>1.5.1-canary.153.215.0</code></summary>
<br />
:sparkles: Test out this PR locally via:
```sh
npm install @artsy/passport@1.5.1-canary.153.215.0
yarn add @artsy/passport@1.5.1-canary.153.215.0
```
</details>
=> chore: Add auto orb to publish package via CI

lib/options.coffee
Add `roles` to user keys that are sent from passport to clients.
Related to https://github.com/artsy/force/pull/6584
https://artsyproduct.atlassian.net/browse/PLATFORM-2492
=> chore: Add roles to user options

lib/app/index.coffee
After some intense troubleshooting it was discovered that this package is pre-empting the force routing code that attempts to do this very same thing.
https://artsy.slack.com/archives/CP9P4KR35/p1613144682324000
h/t @dzucconi
=> feat: Remove personalize routing line

README.md
This updates the README with a note about how code has been moved to force. Will merge once https://github.com/artsy/force/pull/9263 is merged.
=> docs(deprecate): Add notice to README.md
